Fix the google-runtime-int clang-tidy warning
Since the static_core/scripts/clang-tidy/clang_tidy_check.py script uses
'*' as the value for checkers, it enables almost all the clang-tidy
checkers including 'google-runtime-int'. The checker pollutes the output
with the following error for the 'libarkbase/utils/math_helpers.h'
header and all the .cpp files the header is included into:

static_core/libarkbase/utils/math_helpers.h:55:11: error: consider
replacing 'unsigned long long' with 'uint64'
[google-runtime-int,-warnings-as-errors]
constexpr unsigned long long GetIntLog2(const unsigned long long x)
          ^

Because the idea is to have in math_helpers.h exactly the same overloads
for the 'GetIntLog2' function as for the '__builtin_ctz' builtin, the
warning should just be suppressed and no fixed width integer type should
be used.

Test: build

Issue:
https://gitcode.com/openharmony/arkcompiler_runtime_core/issues/9791

Signed-off-by: Howard Roark <howard.roark1@huawei-partners.com>